[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

license = "MIT"
categories = ["games", "simulation"]
description = "A chess engine built in Rust."
keywords = ["chess"]
readme = "README.md"
repository = "https://github.com/hafihaf123/chess_engine"

[dependencies]
